language: go

python:
  - master
go:
  - master

install:
  - go get github.com/gohugoio/hugo

before_script:
  - rm -rf public || exit 0

script:
    - hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: $GITHUB_EMAIL
  name: $GITHUB_USERNAME
  verbose: true
  keep-history: true
  local-dir: public
  target_branch: gh-pages
  on:
    branch: master

after_success:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --quiet --force https://$REPO_TOKEN@github.com/argsno/argsno.github.io.git master